name: flutterwave
description: Flutterwave's forked library that wraps the standard implementation.
version: 1.0.0
homepage: https://github.com/Princeyyyy/flutterwave
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  fluttertoast: ^8.2.8
  flutter_inappwebview: ^6.0.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.4
